Add python3.11 support
KaiL4eK/pyproject-cookiecutter pull request #35
Opened 2024-02-04 19:21 UTC by serykhelena

2024-02-06 08:50 UTC, KaiL4eK requested changes

2024-02-06 08:50 UTC, KaiL4eK commented on test-configs/py311-poetry-docker-github.yaml
Может добавить тестирование этой версии в CI?

2024-02-06 18:02 UTC, serykhelena commented
Добалены проверки для python 3.11

2024-02-08 13:42 UTC, KaiL4eK approved these changes

2024-02-08 17:45 UTC, merged