Updates for poetry >= 1.7.0
KaiL4eK/pyproject-cookiecutter pull request #41
Opened 2024-02-06 21:07 UTC by serykhelena

2024-02-06 21:12 UTC, serykhelena commented
@KaiL4eK  В проверках с питоном 3.10 повысила версию поетри до 1.7.0 
Можно так оставить или лучше отдельную сделать?

2024-02-08 13:45 UTC, KaiL4eK requested changes
Мне кажется нужен тестик на обратную совместимость либо описать, до какой версии обратно поддерживаем

2024-03-02 19:21 UTC, serykhelena commented
Обновила версии actions - https://github.com/actions/setup-python

2024-03-04 09:13 UTC, KaiL4eK approved these changes

2024-03-27 07:50 UTC, merged