Feature/43 add ruff and update
KaiL4eK/pyproject-cookiecutter pull request #44
Opened 2024-09-16 19:21 UTC by KaiL4eK

- Added ruff formatter and linter
- Updated core project packages
- Updated readmes
- Added commands for Makefile
- Added test for poetry 180

2024-09-17 18:43 UTC, serykhelena requested changes

2024-09-17 18:43 UTC, serykhelena commented on {{ cookiecutter.project_name }}/tests/test_example/__init__.py
Зачем init-файл в тестах?

2024-09-17 18:45 UTC, serykhelena commented
![image](https://github.com/user-attachments/assets/34d7c9d1-3750-496f-98f6-d690b2df8dd4)

ruff может быть и линтером и форматтером?

2024-09-17 18:50 UTC, KaiL4eK commented
> ![image](https://github.com/user-attachments/assets/34d7c9d1-3750-496f-98f6-d690b2df8dd4)
> 
> ruff может быть и линтером и форматтером? 

Да

2024-09-17 19:24 UTC, KaiL4eK commented on {{ cookiecutter.project_name }}/tests/test_example/__init__.py
Это было требованием одного из правил ruff, закрыл его для тестов

2024-09-18 07:03 UTC, serykhelena approved these changes

2024-09-18 07:12 UTC, merged